/**
 * Created by jtun02 on 15/11/13.
 */
require.config({
    path:{
        'angular':'../../framework/1.3.0.14/angular.js',
        'ui-router':'../../ui-router/angular-ui-router.min.js',
        'angular-sanitize':'../../framework/1.3.0.14/angular-sanitize.js'
    },
    shim:{
        'angular':{
            exports:'angular'
        },
        'ui-router':{
            deps:['angular'],
            exports:'ui-router'
        }
    }
})